_target_: perturbench.modelcore.models.DecoderOnly
n_genes: null
n_perts: null

## Optimizer params
lr: 6.72106935566634e-05
wd: 7.90200208844498e-09

## Model params
n_layers: 3
encoder_width: 3072
softplus_output: True
use_covariates: True
use_perturbations: True